global:
  environment: production
  revisionHistoryLimit: 12
  dockerconfigjson: ew0KICAgICAgICAiYXV0aHMiOiB7DQogICAgICAgICAgICAgICAgImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMDFOVE02WjJ4a2RDMHpRM1pMU0c5NmNEVndTRWhqTTJFM2MycEZZdz09Ig0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KfQ==

  frontend:
    replicas: 1
    image: gitlab.praktikum-services.ru:5050/std-024-29/sausage-store/sausage-frontend
    tag: latest
    fqdn: sergey-danilov-24.k8s.praktikum-services.tech

  backend:
    image: gitlab.praktikum-services.ru:5050/std-024-29/sausage-store/sausage-backend
    tag: latest
    replicas: 3
    spring_datasource_username: ${SPRING_DATASOURCE_USERNAME}
    spring_datasource_password: ${SPRING_DATASOURCE_PASSWORD}
    spring_datasource_url: ${SPRING_DATASOURCE_URL}
    spring_data_mongodb_uri: ${SPRING_DATA_MONGODB_URI}
    report_path: /app/reports
    log_path: /app/logs
    minallowed_cpu: 0m
    minallowed_memory: 0Mi
    maxallowed_cpu: 1000m
    maxallowed_memory: 512Mi

  backend_report:
    image: gitlab.praktikum-services.ru:5050/std-024-29/sausage-store/sausage-backend-report
    tag: latest
    replicas: 1
    db: ${REPORTS_MONGODB_URI}
    requests_memory: 64Mi
    requests_cpu: 100m
    limits_memory: 256Mi
    limits_cpu: 200m
