---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    Z2l0bGFiK2RlcGxveS10b2tlbi01NTM6Z2xkdC0zQ3ZLSG96cDVwSEhjM2E3c2pFYw==
type: kubernetes.io/dockerconfi
