---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ew0KICAgICAgICAiYXV0aHMiOiB7DQogICAgICAgICAgICAgICAgImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMDFOVE02WjJ4a2RDMHpRM1pMU0c5NmNEVndTRWhqTTJFM2MycEZZdz09Ig0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KfQ==
type: kubernetes.io/dockerconfigjson