---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAvc3RkLTAyNC0yOS9zYXVzYWdlLXN0b3JlIjp7InVzZXJuYW1lIjoiZ2l0bGFiK2RlcGxveS10b2tlbi01NTMiLCAicGFzc3dvcmQiOiAiZ2xkdC0zQ3ZLSG96cDVwSEhjM2E3c2pFYyJ9fX0K
type: kubernetes.io/dockerconfi
