- name: Reload backend
  ansible.builtin.service:
    name: backend
    daemon_reload: true
    enabled: true
  become: true

- name: Restart backend
  ansible.builtin.service:
    name: backend
    state: restarted
  become: true
