stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.22.6
  environment:
    name: kubernetes
    url: ${K8S_URL}
  before_script:
    - mkdir ~/.kube
    - echo ${KUBECONFIG} > ~/.kube/config
    - cat ~/.kube/config
    - export KUBECONFIG=$(find ~/.kube -maxdepth 1 -type f -name '*' | tr "\n" ":")
  script:
    - kubectl apply -f kubernetes/backend/
    - kubectl apply -f kubernetes/backend-report/
    - kubectl apply -f kubernetes/frontend/
    - rm -f ~/.kube/config
