stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.26.14
  environment:
    name: kubernetes
    url: https://sergey-danilov-24.k8s.praktikum-services.tech/
  before_script:
    # - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    # - cp kubectl /usr/local/bin/
    # - chmod +x /usr/local/bin/kubectl
    - mkdir ~/.kube
    - echo ${KUBECONFIG} | base64 -d > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
  script:
    - for file in kubernetes/backend/*.yaml; do envsubst < $file | kubectl apply -f -; done
    # - for file in kubernetes/backend-report/*.yaml; do envsubst < $file | kubectl apply -f  -; done
    - cd kubernetes/backend-report/
    - envsubst < deployment.yaml | kubectl apply -f  -
    - kubectl apply -f hpa.yaml
    - kubectl apply -f service.yaml
    - kubectl apply -f kubernetes/frontend/
    - rm -f ~/.kube/config
