stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/k8s:1.26.12
  environment:
    name: kubernetes
    url: ${K8S_URL}
  before_script:
    - mkdir ~/.kube
    - echo ${KUBECONFIG} | base64 -d > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
  script:
    - kubectl apply -f kubernetes/backend/
    - kubectl apply -f kubernetes/backend-report/
    - kubectl apply -f kubernetes/frontend/
    - rm -f ~/.kube/config
