---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ew0KICAgICAgICAiYXV0aHMiOiB7DQogICAgICAgICAgICAgICAgImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIkNBdnY3WnhxaG1zemdzdTVZdHBlIg0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KfQ==
type: kubernetes.io/dockerconfigjson